CREATE TABLE EMPLOYEES (
	ID LONG,
	NAME VARCHAR,
	SURNAME VARCHAR,
	FATHER_NAME VARCHAR,
	BIRTH_DATE DATE,
	SALARY INT,
	GRADE LONG,
    POST LONG,
    DEPARTMENT LONG,
	CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
)

CREATE TABLE DEPARTMENT (
	ID NUMBER,
	NAME VARCHAR,
	HEAD_EMPLOYEE_ID NUMBER,
	CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID)
)

CREATE TABLE CERTIFICATE (
	ID" INT,
	DATE" DATE,
	COMPANY" VARCHAR2,
	NAME" VARCHAR2,
	CERT_NUMBER LONG,
	"SCAN" BLOB,
	CONSTRAINT CERTIFICATE_PK PRIMARY KEY ("ID")
)

CREATE TABLE "POST" (
	"ID" INT,
	"NAME" VARCHAR2,
	"IS_HEAD" NUMBER,
	CONSTRAINT POST_PK PRIMARY KEY ("ID")
)

CREATE TABLE "DEP_HAS_PARENT_DEP" (
	"DEPARTMENT_ID" INT,
	"PARENT_DEPARTMENT_ID" INT,
	CONSTRAINT DEP_HAS_PARENT_DEP_PK PRIMARY KEY ("DEPARTMENT_ID","PARENT_DEPARTMENT_ID")
)

CREATE TABLE "GRADE" (
	"ID" INT,
	"NAME" CHAR,
	CONSTRAINT GRADE_PK PRIMARY KEY ("ID")
)