CREATE TABLE CERTIFICATE (
	ID NUMBER(*) PRIMARY KEY,
	RECEIVE_DATE DATE,
	COMPANY NVARCHAR2(90),
	NAME NVARCHAR2(90),
	CERT_NUMBER NUMBER(*),
	SCAN_ID NUMBER NOT NULL
);

CREATE TABLE SCAN (
	ID NUMBER(*) PRIMARY KEY,
	SCAN BLOB NOT NULL
);

CREATE TABLE GRADE (
	ID NUMBER(*) PRIMARY KEY,
	NAME NVARCHAR2(90)
);

CREATE TABLE POST (
	ID NUMBER(*) PRIMARY KEY,
	NAME NVARCHAR2(90)
);

CREATE TABLE DEPARTMENT (
	ID NUMBER(*) PRIMARY KEY,
	NAME NVARCHAR2(90),
	HEAD_EMPLOYEE_ID NUMBER(*)
);

CREATE TABLE EMPLOYEE (
	ID NUMBER(*) PRIMARY KEY,
	NAME NVARCHAR2(90),
	SURNAME NVARCHAR2(90),
	FATHER_NAME NVARCHAR2(90),
	BIRTH_DATE DATE,
	SALARY NUMBER(*),
    POST_ID NUMBER(*),
	GRADE_ID NUMBER(*),
    DEPARTMENT_ID NUMBER(*),
	CERTIFICATE_ID NUMBER(*)
);

CREATE TABLE DEP_HAS_PARENT_DEP (
	DEPARTMENT_ID NUMBER(*),
	PARENT_DEPARTMENT_ID NUMBER(*)
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_HAS_HEAD_FK
FOREIGN KEY (HEAD_EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);

ALTER TABLE CERTIFICATE ADD	CONSTRAINT CERTIFICATE_HAS_SCAN_FK
FOREIGN KEY (SCAN_ID) REFERENCES SCAN (ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_HAS_POST_FK
FOREIGN KEY (POST_ID) REFERENCES POST (ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_HAS_GRADE_FK
FOREIGN KEY (GRADE_ID) REFERENCES GRADE (ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_HAS_DEPARTMENT_FK
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_HAS_CERTIFICATE_FK
FOREIGN KEY (CERTIFICATE_ID) REFERENCES CERTIFICATE (ID);

ALTER TABLE DEP_HAS_PARENT_DEP ADD	CONSTRAINT DEPARTMENT_FK
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID);
ALTER TABLE DEP_HAS_PARENT_DEP ADD	CONSTRAINT PARENT_FK
FOREIGN KEY (PARENT_DEPARTMENT_ID) REFERENCES DEPARTMENT (ID);